export default function Head() {
  return (
    <head>
      <title>Yshoes Collections</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"></link>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Assistant"></link>
    </head>
  )
}
