###
GET http://localhost:3001/v1/yshoes/users/63f1280f1376cc5bcd198644

###
POST http://localhost:3001/v1/yshoes/users/
Content-Type: application/json

{
    "name": "holaa",
    "username": "holaaaa",
    "password": "hola",
    "email": "holaa@holaasddaa.com"
}


###
PUT http://localhost:3001/v1/yshoes/users/63f1280f1376cc5bcd198644
Content-Type: application/json

{
    "name": "",
    "username": "asdas",
    "password": "aasasd",
    "email": "holaa@ola"
}

###
DELETE  http://localhost:3001/v1/yshoes/users/63f1280f1376cc5bcd198644