###
GET http://localhost:3001/v1/yshoes/users/63f12ef621190660a2e21d7f

###
POST http://localhost:3001/v1/yshoes/users/
Content-Type: application/json

{
    "name": "holaa",
    "username": "holaaasdasdaa",
    "password": "hola",
    "email": "holaa@holasdasaasddaa.com"
}


###
PUT http://localhost:3001/v1/yshoes/users/63f12ef621190660a2e21d7f
Content-Type: application/json

{
    "name": "asdasdasd asdasdasd",
    "username": "asdas",
    "password": "aasasd",
    "email": "holaa@ol.a"
}

###
DELETE  http://localhost:3001/v1/yshoes/users/63f1280f1376cc5bcd198644

###
POST http://localhost:3001/v1/ensure-process/ensure
Content-Type: application/json

{
    "ensure": true
}