###
GET http://localhost:3001/v1/yshoes/cart/63f3a5c8a2543b181dc25c0f

###
POST http://localhost:3001/v1/yshoes/cart/add/63f3a5c8a2543b181dc25c0f
Content-Type: application/json

{
    "id_product": "63f21521bac6480a4aa3bfd3",
    "size": "extralarge",
    "color": "blue"
}

###
POST http://localhost:3001/v1/yshoes/cart/remove/63f3a5c8a2543b181dc25c0f
Content-Type: application/json

{
    "id_in_cart": "63f248e29db30f47e8f3d02c"
}
